from pdf2image import convert_from_bytes
import io
def pdf_2_image_converter(file_bytes):
    # to check the file format in the fast api use the method 'content_type' of the upload file object
    pages = convert_from_bytes(file_bytes, 300,poppler_path=r'E:\D07.Niraj G\KFT03-D-M\Data Science H Drive\Py-s_wares\poppler-0.68.0\bin')
    img_byte_arr = io.BytesIO()
    pages[0].save(img_byte_arr,format='PNG')
    final_image_byte_arr = img_byte_arr.getvalue()
    return final_image_byte_arr


# def extract_text_from_pdf_bytes(pdf_bytes: bytes) -> str:
#     text = ""
#     try:
#         with fitz.open(stream=pdf_bytes, filetype="pdf") as doc:
#             for page in doc:
#                 text += page.get_text()
#     except Exception as e:
#         raise RuntimeError("Failed to read PDF: " + str(e))
#     return text


# # --- All your other functions go here: ---
# # extract_transaction_history()
# # clean_multiline_strings()
# # extract_cersai_structured_data() ← this needs to use the bytes version now

# def extract_transaction_history(text: str) -> List[Dict]:
#     lines = text.splitlines()
#     transactions = []
#     i = 0
#     while i < len(lines) - 8:
#         if re.match(r'^\d+\s*$', lines[i].strip()) and re.match(r'^\d{9,}$', lines[i + 1].strip()):
#             try:
#                 txn = {
#                     "S.No": lines[i].strip(),
#                     "Transaction ID": lines[i + 1].strip(),
#                     "Type of SI": f"{lines[i + 2].strip()} {lines[i + 3].strip()}",
#                     "Type of Transaction": lines[i + 4].strip(),
#                     "Created By": lines[i + 5].strip().split()[0],
#                     "Creation Timestamp": " ".join(lines[i + 5].strip().split()[1:]) + " " + lines[i + 6].strip(),
#                     "Modified/Approved By": lines[i + 7].strip(),
#                     "Modification Timestamp": lines[i + 8].strip()
#                 }
#                 transactions.append(txn)
#                 i += 9
#             except Exception:
#                 i += 1
#         else:
#             i += 1
#     return transactions


# def clean_multiline_strings(data):
#     if isinstance(data, dict):
#         return {
#             key: clean_multiline_strings(value)
#             if isinstance(value, (dict, list)) else ' '.join(value.split())
#             for key, value in data.items()
#         }
#     elif isinstance(data, list):
#         return [clean_multiline_strings(item) for item in data]
#     else:
#         return data


# def extract_cersai_structured_data_from_bytes(pdf_bytes: bytes) -> Dict:
#     full_text = extract_text_from_pdf_bytes(pdf_bytes)

#     def get(pattern, group=1, flags=0):
#         match = re.search(pattern, full_text, flags)
#         try:
#             return " ".join(match.group(group).split()) if match else ""
#         except IndexError:
#             return match.group(0).strip() if match else ""

#     final_result = {
#         "Asset_ID": get(r"Asset ID\s*(\d+)"),
#         "Asset_Category": get(r"Asset Category\s*([A-Za-z]+)"),
#         "Type_of_Asset": get(r"Type Of Asset\s*([A-Za-z]+)"),
#         "Area": get(r"Area\s*([\d.]+)"),
#         "Area_Unit": get(r"Area Unit\s*(Square Feet|Square Meters|Sq Ft|Sq Mt)"),
#         "Created_By": get(r"Created By\s*([A-Z0-9]+)"),
#         "Details_Of_Charge": get(r"Details Of Charge\s*([A-Za-z ]+)"),
#         "Entity_Identification_Number": get(r"Entity Identification Number\s*([A-Z0-9]+)"),
#         "SI_Creation_Date_In_Bank": get(r"SI Creation Date In Bank\s*([\d-]+)"),
#         "SI_Registration_Date_In_CERSAI_Portal": get(r"SI Registration Date In CERSAI Portal\s*([\d\-: ]+)"),
#         "Satisfaction_Status": get(r"Satisfaction Status\s*([A-Za-z ]+)"),
#         "Security_Interest_ID": get(r"Security Interest ID\s*(\d+)"),
#         "Total_Secured_Amount": get(r"Total Secured Amount\s*([\d.]+)"),
#         "Transaction_Id": get(r"Transaction Id\s*(\d+)"),
#         "Type_Of_Finance": get(r"Type Of Finance\s*([A-Za-z]+)"),
#         "Type_Of_Security_Interest": get(r"Type Of Security Interest\s*([A-Za-z ]+)"),
#         "Description_Of_Asset": get(r"Description Of Asset\s*(.*)"),
#         "Survey_Number_Municipal Number": get(r"Survey Number\s*/\s*Municipal Number\s*(.*)"),
#         "Name_of_the_Institution": get(r"Name of the Institution\s*(.*?)\n"),
#         "Institution_GSTIN": get(r"Institution GSTIN\s*([A-Z0-9]+)"),
#         "Report_Download_Date": get(r"Report Download Date\s*([\d\-:. ]+)"),
#         "Transaction_ID_QRF_NO": get(r"Transaction ID\s*/\s*QRF NO\s*(\d+)"),
#         "Generated_by": get(r"Generated by\s*(.*?\([A-Z0-9]+\))", group=1, flags=re.IGNORECASE),

#         "Property_Address": {
#             "Building_Tower_Name_Number": get(r"Building / Tower Name / Number\s*(.+?)\n"),
#             "Floor_No": get(r"Floor No\s*(.+?)\n"),
#             "House_Flat_Number_Unit_No": get(r"House / Flat Number / Unit No\s*(.+?)\n"),
#             "Name_of_the_Project_Scheme_Society_Zone": get(r"Name of the Project / Scheme / Society / Zone\s*(.+?)\n"),
#             "Street Name_Number": get(r"Street Name / Number\s*(.*?)\n"),
#             "Locality": get(r"Locality / Sector\s*(.*?)\n"),
#             "City": get(r"City / Town / Village\s*(.*?)\n"),
#             "District": get(r"District\s*(.+?)\n"),
#             "State": get(r"State / UT\s*(.+?)\n"),
#             "Pincode": get(r"Pin Code / Post Code\s*(\d{6})")
#         },
#         "Charge_Holder_Details": {
#             "Name": "",
#             "Branch": ""
#         },
#         "Borrower_Details": [],
#         "Asset_Owner_Details": [],
#         "Transaction_History": extract_transaction_history(full_text)
#     }

#     charge_holder_match = re.search(
#         r"Charge Holder Name\s*(.*?)\s*(Office / Ward / Branch Name\s*)?(.*?)(?=Transaction|Original View|Security Interest ID|Page No|$)",
#         full_text,
#         re.IGNORECASE | re.DOTALL,
#     )
#     if charge_holder_match:
#         combined_line = " ".join(charge_holder_match.group(1, 3)).strip()
#         parts = combined_line.split()
#         if len(parts) > 1:
#             final_result["Charge_Holder_Details"]["Branch"] = parts[-1]
#             final_result["Charge_Holder_Details"]["Name"] = " ".join(parts[:-1])
#         else:
#             final_result["Charge_Holder_Details"]["Name"] = combined_line

#     borrower_block = re.findall(
#         r"(\d+)\s+(Sole Proprietorship|Partnership Firm|Individual|Company)\s+([A-Z\s]+?)\s+([A-Z\s]+|NA)\s+(Yes|No)",
#         full_text,
#         re.IGNORECASE
#     )
#     unique_borrowers = set()
#     for b in borrower_block:
#         borrower_tuple = (b[1].strip(), b[2].strip(), b[3].strip(), b[4].strip())
#         unique_borrowers.add(borrower_tuple)

#     final_result["Borrower_Details"] = [
#         {
#             "Type_of_Borrower": t,
#             "Name_of_the_Borrower": n,
#             "Father_Mother_Name": f,
#             "Is_Borrower_Asset_Owner?": o
#         }
#         for (t, n, f, o) in unique_borrowers
#     ]

#     asset_owner_block_match = re.search(
#         r"Asset Owner\(s\) Details\s+(.*?)\s+Holder Details",
#         full_text,
#         re.IGNORECASE | re.DOTALL
#     )
#     if asset_owner_block_match:
#         asset_owner_block = asset_owner_block_match.group(1)
#         asset_owner_matches = re.findall(
#             r"\d+\s+(Individual|Sole Proprietorship|Company|Firm)\s+([A-Z ]{3,})\s+([A-Z]+)",
#             asset_owner_block,
#             re.IGNORECASE
#         )
#         for typ, name, parent in asset_owner_matches:
#             final_result["Asset_Owner_Details"].append({
#                 "Type": typ.strip(),
#                 "Name": name.strip(),
#                 "Father_Mother_Name": parent.strip()
#             })

#     return {"Final_result": final_result}

# @app.post("/CERSAI_PDF")
# async def extract_cersai_endpoint(request: Request, pdf_file: UploadFile = File(...)):
#     logger.info(f"Request from {request.client.host}")
#     logger.info("Received a CERSAI PDF file")

#     req_id = str(uuid.uuid4())
#     output_dir = f"../completed_requests/{req_id}"
#     os.makedirs(output_dir, exist_ok=True)

#     try:
#         # Read PDF bytes and extract data directly
#         pdf_file_bytes = await pdf_file.read()
        
#         # Extract CERSAI data from PDF bytes
#         extracted_data = extract_cersai_structured_data_from_bytes(pdf_file_bytes)
#         combined_result = extracted_data.get('Final_result', {})

#         # Clean multiline strings
#         cleaned_data = {'Final_result': clean_multiline_strings(combined_result)}

#         # Save the output to disk for debugging/auditing
#         with open(os.path.join(output_dir, "extracted_data.json"), "w") as f:
#             import json
#             json.dump(cleaned_data, f, indent=2)

#         # Return result
#         return JSONResponse(
#             content={
#                 "status": "success", 
                
#                 "data": cleaned_data
#             }
#         )

#     except Exception as e:
#         logger.error(f"Error during CERSAI PDF processing: {str(e)}", exc_info=True)
#         return JSONResponse(
#             status_code=500, 
#             content={
#                 "status": "error", 
#                 "message": "Internal server error", 
#                 "details": str(e)
#             }
#         )